import { test, expect } from '@playwright/test'

test.describe('Loading Component E2E', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/testing/loading')
  })

  test('The full-screen Loading state should display correctly and fill the screen', async ({
    page,
  }) => {
    const fullPageLoader = page.locator('app-loading-state').first()

    // Verify text display
    await expect(fullPageLoader).toContainText('Preparing your data')
    await expect(fullPageLoader).toContainText('This may take a few seconds...')

    // Verify key CSS properties (classes generated by fullPage=true)
    const container = fullPageLoader.locator('div').first()
    await expect(container).toHaveClass(/min-h-screen/)

    // Verify that the projected button is clickable
    const cancelBtn = page.getByRole('button', { name: 'Cancel Task' })
    await expect(cancelBtn).toBeVisible()
  })

  test('Spinners of all sizes should render, and their animations should function correctly', async ({
    page,
  }) => {
    // Verify that cards for all 3 sizes are present
    const loaders = page.locator('app-loading-state:not([data-fullpage="true"])')
    await expect(loaders).toHaveCount(3)

    // Verify that the animation class is present
    const spinner = page.locator('app-loading-spinner').first().locator('ng-icon')
    await expect(spinner).toHaveClass(/animate-spin/)

    // Verify that the SVG is actually rendered (dependent on the ng-icon implementation)
    const svg = spinner.locator('svg')
    await expect(svg).toBeVisible()
  })
})
