import { ApplicationConfig, provideZoneChangeDetection } from '@angular/core'
import { provideRouter } from '@angular/router'
import { provideIcons } from '@ng-icons/core'
import {
  lucideHome,
  lucideClipboardList,
  lucideLayoutDashboard,
  lucideChevronLeft,
  lucideChevronRight,
  lucideX,
  lucideMenu,
  lucideUser,
  lucideImage,
  lucideFileText,
  lucideMusic,
  lucideTrash2,
  lucideCheck,
  lucideMinus,
  lucideCircle,
  lucideUpload,
  lucideLoader2,
  lucideCopy,
  lucideChevronUp,
  lucideChevronDown,
  lucideInfo,
  lucideCheckCircle,
  lucideSun,
  lucideMoon,
  lucideBot,
  lucideWorkflow,
  lucidePlus,
  lucideExternalLink,
  lucideRotateCcw,
  lucideSendHorizontal,
  lucideSquare,
  lucidePaperclip,
  lucideDownload,
  lucideLightbulb,
  lucideBookOpen,
  lucideTriangleAlert,
  lucideKey,
  lucideArrowLeft,
  lucidePackage,
  lucideFolderOpen,
  lucideDatabase,
  lucideGlobe,
  lucideXCircle,
} from '@ng-icons/lucide'

import { routes } from './app.routes'
import { THEME_CONFIG } from './devui/services/theme.service'

export const appConfig: ApplicationConfig = {
  providers: [
    {
      provide: THEME_CONFIG,
      useValue: {
        attribute: 'class',
        defaultTheme: 'dark',
        enableSystem: true,
        disableTransitionOnChange: true,
      },
    },
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes),

    provideIcons({
      lucideHome,
      lucideClipboardList,
      lucideLayoutDashboard,
      lucideChevronLeft,
      lucideChevronRight,
      lucideX,
      lucideMenu,
      lucideUser,
      lucideImage,
      lucideFileText,
      lucideMusic,
      lucideTrash2,
      lucideCheck,
      lucideMinus,
      lucideCircle,
      lucideUpload,
      lucideLoader2,
      lucideCopy,
      lucideChevronUp,
      lucideChevronDown,
      lucideInfo,
      lucideCheckCircle,
      lucideSun,
      lucideMoon,
      lucideBot,
      lucideWorkflow,
      lucidePlus,
      lucideExternalLink,
      lucideRotateCcw,
      lucideSendHorizontal,
      lucideSquare,
      lucidePaperclip,
      lucideDownload,
      lucideLightbulb,
      lucideBookOpen,
      lucideTriangleAlert,
      lucideKey,
      lucideArrowLeft,
      lucidePackage,
      lucideFolderOpen,
      lucideDatabase,
      lucideGlobe,
      lucideXCircle,
    }),
  ],
}
